#version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
        - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    restart: "always"
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BROKER_CONNECT: kafka:9092
#      JVM_OPTS: "-Xms32M -Xmx64M"
#    depends_on:
#      - kafka

  postgres:
    image: postgres:15
    container_name: sensorium-postgres
    environment:
      POSTGRES_DB: sensorium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
